spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: uso800
  jpa:
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        formatSql: true
  mail:
    host: smtp.gmail.com
    port: 587
      # あなたのGMailのアドレス
    username: program.kiyomori@gmail.com
        # アプリ パスワード
    password: ulucvhbycibbpvsc
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.ssl.trust: smtp.gmail.com